### ISSUE TITLE
Out of date information on FAQ

### ISSUE THREAD

**Issue by felipelalli** [coinkite/coinkite-docs#15]
Hi! In [FAQ](https://coldcardwallet.com/docs/faq) we can find:

> Can I have multiple wallets in each Coldcard?
> There is a **single "wallet"**, derived from the BIP39 seed words. In addition, we have an optional "duress" wallet, which is derived from the wallet's seed words and is not independent. This means it gets backed-up automatically, and the original seed words also backup the duress wallet.

But in [Settings DOC](https://coldcardwallet.com/docs/settings) we find:

> There are two "wallets" in each Coldcard (...)

And also:

> Both the main and secondary wallets have a derived "duress" wallet (...)

So in total are 4 wallets, aren't them?

**Comment by felipelalli** [comment]
PS: I didn't make the change myself because I need to understand if I understood correctly or if I missed something.

**Comment by peter-conalgo** [comment]
It’s a Mk2 vs. Mk3 difference. We need to make that clear. Mk3 doesn’t have a secondary wallet.

**Comment by felipelalli** [comment]
> It’s a Mk2 vs. Mk3 difference. We need to make that clear. Mk3 doesn’t have a secondary wallet.

Thank you. But do you know the motivation to this specific change between Mk2 and Mk3?

**Comment by peter-conalgo** [comment]
The way we use the 608 secure element in Mk3 doesn't allow us to securely store a second wallet. 

I am updating the docs right now about this.
