### ISSUE TITLE
Start new line for each sentence, remove block text

### ISSUE THREAD

**Issue by MaxHillebrand** [coinkite/coinkite-docs#2]
Currently, all mark down files have a block text that breaks when a specific number of characters are in the line. This makes it very difficult to edit a file in the GitHub gui especially. I think it would be better to change this so that a line can be as long as it needs be.

Further, in Wasabi documentation we use the writing convention that a new sentence starts a new line. This makes reviewing PRs more approachable, since it is more clear what is edited. Also that the number of lines added or subtracted now aligns with the number of sentences added or subtracted, which makes repo analysis  more useful.

**Comment by peter-conalgo** [comment]
Those are both good practises, but to implement them now would require a diff on every line of the project.

I'll see if I can follow them on new text being written (for HSM and CKBunker)

**Comment by MaxHillebrand** [comment]
Yes, this would generate a lot of diff... 
though shall I do it with any file that I change from now on?

**Comment by peter-conalgo** [comment]
No, please don't do that.

I want to keep the current style. It works better with my editor, and yields better markdown (when viewed as text).... and I could make other excuses, but just my preference.
